openapi: 3.0.3
info:
  title: DataAfrik API
  version: 1.0.0
  description: >
    API-first contract for DataAfrik domain services. This v1 spec is a migration
    baseline and is expanded incrementally while legacy endpoints remain active.
servers:
  - url: /api/v1
tags:
  - name: system
  - name: auth
  - name: blog
  - name: comments
  - name: reports
  - name: subscriptions
  - name: finance
paths:
  /:
    get:
      tags: [system]
      summary: API capability document
      responses:
        '200':
          description: API metadata
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SuccessEnvelope'
  /system/health:
    get:
      tags: [system]
      summary: Health check
      responses:
        '200':
          description: Service is healthy
  /auth/supabase/sign-in:
    post:
      tags: [auth]
      summary: Sign in via Supabase-backed server flow
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required: [email, password]
              properties:
                email:
                  type: string
                  format: email
                password:
                  type: string
      responses:
        '200':
          description: Authenticated
        '401':
          description: Invalid credentials
  /blog/posts:
    get:
      tags: [blog]
      summary: List blog posts
      parameters:
        - in: query
          name: page
          schema: { type: integer, minimum: 1 }
        - in: query
          name: limit
          schema: { type: integer, minimum: 1, maximum: 200 }
      responses:
        '200':
          description: Posts list
  /blog/posts/{slug}:
    get:
      tags: [blog]
      summary: Fetch a post by slug
      parameters:
        - in: path
          name: slug
          required: true
          schema: { type: string }
      responses:
        '200':
          description: Post resolved
        '404':
          description: Not found
  /blog/posts/{slug}/like:
    post:
      tags: [blog]
      summary: Like a blog post
      security:
        - bearerAuth: []
      parameters:
        - in: path
          name: slug
          required: true
          schema: { type: string }
      responses:
        '200':
          description: Like accepted
  /comments/post/{postId}:
    get:
      tags: [comments]
      summary: List comments for a post
      parameters:
        - in: path
          name: postId
          required: true
          schema: { type: string }
      responses:
        '200':
          description: Comment list
  /comments:
    post:
      tags: [comments]
      summary: Create comment
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
      responses:
        '201':
          description: Comment created
  /reports/request:
    post:
      tags: [reports]
      summary: Submit custom report request
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
      responses:
        '201':
          description: Request accepted
  /finance/ingestion/jobs:
    post:
      tags: [finance]
      summary: Queue finance ingestion job
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required: [rows]
              properties:
                rows:
                  type: array
                  items:
                    type: object
                mapping:
                  type: object
                options:
                  type: object
      responses:
        '202':
          description: Job queued
        '200':
          description: Existing idempotent job reused
  /finance/reconciliation/jobs:
    post:
      tags: [finance]
      summary: Queue bank reconciliation job
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required: [bankRows]
              properties:
                bankRows:
                  type: array
                  items:
                    type: object
                bankMapping:
                  type: object
                bookRows:
                  type: array
                  items:
                    type: object
                bookTransactions:
                  type: array
                  items:
                    type: object
                bookMapping:
                  type: object
                options:
                  type: object
      responses:
        '202':
          description: Job queued
        '200':
          description: Existing idempotent job reused
  /finance/reports/jobs:
    post:
      tags: [finance]
      summary: Queue financial summary report job
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                transactions:
                  type: array
                  items:
                    type: object
                rows:
                  type: array
                  items:
                    type: object
                mapping:
                  type: object
                options:
                  type: object
                companyName:
                  type: string
                reportPeriod:
                  type: string
      responses:
        '202':
          description: Job queued
        '200':
          description: Existing idempotent job reused
  /finance/jobs:
    get:
      tags: [finance]
      summary: List authenticated user's finance jobs
      security:
        - bearerAuth: []
      parameters:
        - in: query
          name: page
          schema: { type: integer, minimum: 1 }
        - in: query
          name: limit
          schema: { type: integer, minimum: 1, maximum: 100 }
        - in: query
          name: type
          schema: { type: string }
        - in: query
          name: status
          schema: { type: string }
      responses:
        '200':
          description: Job list
  /finance/jobs/{jobId}:
    get:
      tags: [finance]
      summary: Get finance job status/result
      security:
        - bearerAuth: []
      parameters:
        - in: path
          name: jobId
          required: true
          schema: { type: string, format: uuid }
      responses:
        '200':
          description: Job details
        '404':
          description: Job not found
  /finance/jobs/storage-mode:
    get:
      tags: [finance]
      summary: Get active finance job storage mode
      security:
        - bearerAuth: []
      responses:
        '200':
          description: Storage mode info
  /subscriptions/plans:
    get:
      tags: [subscriptions]
      summary: Available plans
      responses:
        '200':
          description: Plan list
  /subscriptions/pdf-pricing:
    get:
      tags: [subscriptions]
      summary: PDF pricing
      responses:
        '200':
          description: Pricing details
  /subscriptions/pdf-checkout:
    post:
      tags: [subscriptions]
      summary: Start PDF checkout
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
      responses:
        '200':
          description: Checkout initialized
  /subscriptions/pdf-access:
    get:
      tags: [subscriptions]
      summary: Verify PDF entitlement
      security:
        - bearerAuth: []
      responses:
        '200':
          description: Access state
  /subscriptions/pdf-verify:
    get:
      tags: [subscriptions]
      summary: Verify checkout session/reference
      security:
        - bearerAuth: []
      responses:
        '200':
          description: Verification status
  /subscriptions/newsletter:
    post:
      tags: [subscriptions]
      summary: Subscribe email to newsletter
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required: [email]
              properties:
                email:
                  type: string
                  format: email
      responses:
        '200':
          description: Subscription result
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
  schemas:
    SuccessEnvelope:
      type: object
      properties:
        success:
          type: boolean
          example: true
        data:
          type: object
        meta:
          type: object
          nullable: true
    ErrorEnvelope:
      type: object
      properties:
        success:
          type: boolean
          example: false
        error:
          type: object
          properties:
            code:
              type: string
            message:
              type: string
